In [1]:
import numpy as np

In [2]:
m = np.array(3)
m

array(3)

In [3]:
m.ndim

0

In [4]:
m.shape

()

In [5]:
m.dtype

dtype('int32')

In [6]:
a = np.array(1,2)
a

TypeError: Cannot interpret '2' as a data type

In [8]:
a = np.array([1,2])
a

array([1, 2])

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [12]:
a.ndim

1

In [13]:
a.shape

(5,)

In [14]:
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('int32')

In [16]:
a

array([1, 2, 3, 4, 5])

In [18]:
b

array([1, 2, 3, 4, 5])

In [19]:
a + b

array([ 2,  4,  6,  8, 10])

In [20]:
a*b

array([ 1,  4,  9, 16, 25])

In [21]:
a-b

array([0, 0, 0, 0, 0])

In [22]:
a/b

array([1., 1., 1., 1., 1.])

In [24]:
v = np.array([[1,2,3],[4,5,6]])
v

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
v.ndim

2

In [26]:
v.shape

(2, 3)

In [27]:
s = np.array([[1,2,3],[4,5,6],[9,8,7]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [28]:
s.ndim

2

In [29]:
s.shape

(3, 3)

In [30]:
s.dtype

dtype('int32')

In [35]:
l = np.zeros(5)
l

array([0., 0., 0., 0., 0.])

In [36]:
l.shape

(5,)

In [37]:
l.ndim

1

In [38]:
l.dtype

dtype('float64')

In [43]:
k= np.zeros([5,3])
k

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
k.ndim

2

In [45]:
k.shape

(5, 3)

In [46]:
k.dtype

dtype('float64')

In [53]:
o = np.zeros(5,dtype=int)
o

array([0, 0, 0, 0, 0])

In [54]:
o.dtype

dtype('int32')

In [55]:
np.zeros(5, float)

array([0., 0., 0., 0., 0.])

In [58]:
c = np.zeros([5,5],complex)
c

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [59]:
c.dtype

dtype('complex128')

In [61]:
p = np.zeros([5,2,3],int)
p

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [62]:
p.ndim

3

In [63]:
p.shape

(5, 2, 3)

In [64]:
p.dtype

dtype('int32')

In [65]:
np.zeros([5,5],int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [67]:
d = np.ones(7,int)
d

array([1, 1, 1, 1, 1, 1, 1])

In [68]:
d.dtype

dtype('int32')

In [69]:
e = np.ones(7,float)
e

array([1., 1., 1., 1., 1., 1., 1.])

In [70]:
e.dtype

dtype('float64')

In [71]:
e = np.zeros(shape=(3,5))
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
f = np.zeros(shape=(3,5,2))
f

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [76]:
g = np.zeros(shape=(2,3,4),dtype=int)
g

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [77]:
g.ndim

3

In [78]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [ ]:
np.array([1, 2, 3], dtype=complex)

In [ ]:
np.ones(5)